/*
RustyCoder

Copyright (C) 2012-2015 Chak Wai Yuan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef CODECS_COMMON_H
#define CODECS_COMMON_H

#include "stdafx.h"

#define AUDIO_EXTENSION_DESCRIPTION_AUDIO_INTERCHANGE "Audio Interchange File Format"
#define AUDIO_EXTENSION_DESCRIPTION_AUDIO_INTERCHANGE_W             WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_AUDIO_INTERCHANGE)
#define AUDIO_EXTENSION_AIF "aif"
#define AUDIO_EXTENSION_AIF_W                                       WIDEN_STRING(AUDIO_EXTENSION_AIF)
#define AUDIO_EXTENSION_AIFC "aifc"
#define AUDIO_EXTENSION_AIFC_W                                      WIDEN_STRING(AUDIO_EXTENSION_AIFC)
#define AUDIO_EXTENSION_AIFF "aiff"
#define AUDIO_EXTENSION_AIFF_W                                      WIDEN_STRING(AUDIO_EXTENSION_AIFF)

/*! Do not change the extension to "mpc" to prevent clash with Musepack format extension */
#define AUDIO_EXTENSION_DESCRIPTION_AKAI_MPC_2000 "Akai MPC 2000 Format"
#define AUDIO_EXTENSION_DESCRIPTION_AKAI_MPC_2000_W                 WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_AKAI_MPC_2000)
#define AUDIO_EXTENSION_AMPC "ampc"
#define AUDIO_EXTENSION_AMPC_W                                      WIDEN_STRING(AUDIO_EXTENSION_AMPC)

#define AUDIO_EXTENSION_DESCRIPTION_SUN_MICROSYSTEM "Sun Microsystem Audio Format"
#define AUDIO_EXTENSION_DESCRIPTION_SUN_MICROSYSTEM_W               WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_SUN_MICROSYSTEM)
#define AUDIO_EXTENSION_AU "au"
#define AUDIO_EXTENSION_AU_W                                        WIDEN_STRING(AUDIO_EXTENSION_AU)

#define AUDIO_EXTENSION_DESCRIPTION_AUDIO_VISUAL_RESEARCH "Audio Visual Research Format"
#define AUDIO_EXTENSION_DESCRIPTION_AUDIO_VISUAL_RESEARCH_W         WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_AUDIO_VISUAL_RESEARCH)
#define AUDIO_EXTENSION_AVR "avr"
#define AUDIO_EXTENSION_AVR_W                                       WIDEN_STRING(AUDIO_EXTENSION_AVR)

#define AUDIO_EXTENSION_DESCRIPTION_APPLE_CORE "Apple Core Audio File"
#define AUDIO_EXTENSION_DESCRIPTION_APPLE_CORE_W                    WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_APPLE_CORE)
#define AUDIO_EXTENSION_CAF "caf"
#define AUDIO_EXTENSION_CAF_W                                       WIDEN_STRING(AUDIO_EXTENSION_CAF)

#define AUDIO_EXTENSION_DESCRIPTION_HIDDEN_MARKOV_MODEL_TOOLKIT "Hidden Markov Model Toolkit Speech Recognition Format"
#define AUDIO_EXTENSION_DESCRIPTION_HIDDEN_MARKOV_MODEL_TOOLKIT_W   WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_HIDDEN_MARKOV_MODEL_TOOLKIT)
#define AUDIO_EXTENSION_HTK "htk"
#define AUDIO_EXTENSION_HTK_W                                       WIDEN_STRING(AUDIO_EXTENSION_HTK)

#define AUDIO_EXTENSION_DESCRIPTION_AMIGA "Amiga Audio Format"
#define AUDIO_EXTENSION_DESCRIPTION_AMIGA_W                         WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_AMIGA)
#define AUDIO_EXTENSION_IFF "iff"
#define AUDIO_EXTENSION_IFF_W                                       WIDEN_STRING(AUDIO_EXTENSION_IFF)

#define AUDIO_EXTENSION_DESCRIPTION_GNU_OCTAVE_MATLAB "GNU Octave File / Matlab File"
#define AUDIO_EXTENSION_DESCRIPTION_GNU_OCTAVE_MATLAB_W             WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_GNU_OCTAVE_MATLAB)
#define AUDIO_EXTENSION_MAT "mat"
#define AUDIO_EXTENSION_MAT_W                                       WIDEN_STRING(AUDIO_EXTENSION_MAT)

#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_1 "MPEG Audio Layer I"
#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_1_W            WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_1)
#define AUDIO_EXTENSION_MP1 "mp1"
#define AUDIO_EXTENSION_MP1_W                                       WIDEN_STRING(AUDIO_EXTENSION_MP1)

#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_2 "MPEG Audio Layer II"
#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_2_W            WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_2)
#define AUDIO_EXTENSION_MP2 "mp2"
#define AUDIO_EXTENSION_MP2_W                                       WIDEN_STRING(AUDIO_EXTENSION_MP2)

#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_3 "MPEG Audio Layer III"
#define AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_3_W            WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_MPEG_AUDIO_LAYER_3)
#define AUDIO_EXTENSION_MP3 "mp3"
#define AUDIO_EXTENSION_MP3_W                                       WIDEN_STRING(AUDIO_EXTENSION_MP3)

#define AUDIO_EXTENSION_DESCRIPTION_ENSONIQ_PARIS "Ensoniq PARIS Audio Format"
#define AUDIO_EXTENSION_DESCRIPTION_ENSONIQ_PARIS_W                 WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_ENSONIQ_PARIS)
#define AUDIO_EXTENSION_PAF "paf"
#define AUDIO_EXTENSION_PAF_W                                       WIDEN_STRING(AUDIO_EXTENSION_PAF)

#define AUDIO_EXTENSION_DESCRIPTION_PORTABLE_VOICE "Portable Voice Format"
#define AUDIO_EXTENSION_DESCRIPTION_PORTABLE_VOICE_W                WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_PORTABLE_VOICE)
#define AUDIO_EXTENSION_PVF "pvf"
#define AUDIO_EXTENSION_PVF_W                                       WIDEN_STRING(AUDIO_EXTENSION_PVF)

#define AUDIO_EXTENSION_DESCRIPTION_RIFF_64 "RIFF 64"
#define AUDIO_EXTENSION_DESCRIPTION_RIFF_64_W                       WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_RIFF_64)
#define AUDIO_EXTENSION_RF64 "rf64"
#define AUDIO_EXTENSION_RF64_W                                      WIDEN_STRING(AUDIO_EXTENSION_RF64)

#define AUDIO_EXTENSION_DESCRIPTION_SOUND_DESIGNER_II "Sound Designer II Audio File"
#define AUDIO_EXTENSION_DESCRIPTION_SOUND_DESIGNER_II_W             WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_SOUND_DESIGNER_II)
#define AUDIO_EXTENSION_SD2 "sd2"
#define AUDIO_EXTENSION_SD2_W                                       WIDEN_STRING(AUDIO_EXTENSION_SD2)

#define AUDIO_EXTENSION_DESCRIPTION_MIDI_SAMPLE_DUMP "MIDI Sample Dump Standard Format"
#define AUDIO_EXTENSION_DESCRIPTION_MIDI_SAMPLE_DUMP_W              WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_MIDI_SAMPLE_DUMP)
#define AUDIO_EXTENSION_SDS "sds"
#define AUDIO_EXTENSION_SDS_W                                       WIDEN_STRING(AUDIO_EXTENSION_SDS)

#define AUDIO_EXTENSION_DESCRIPTION_BERKELEY_IRCAM "Berkeley IRCAM CARL Sound File"
#define AUDIO_EXTENSION_DESCRIPTION_BERKELEY_IRCAM_W                WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_BERKELEY_IRCAM)
#define AUDIO_EXTENSION_SF "sf"
#define AUDIO_EXTENSION_SF_W                                        WIDEN_STRING(AUDIO_EXTENSION_SF)

#define AUDIO_EXTENSION_DESCRIPTION_CREATIVE_LABS "Creative Labs Audio Format"
#define AUDIO_EXTENSION_DESCRIPTION_CREATIVE_LABS_W                 WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_CREATIVE_LABS)
#define AUDIO_EXTENSION_VOC "voc"
#define AUDIO_EXTENSION_VOC_W                                       WIDEN_STRING(AUDIO_EXTENSION_VOC)

#define AUDIO_EXTENSION_DESCRIPTION_WAV "WAV"
#define AUDIO_EXTENSION_DESCRIPTION_WAV_W                           WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_WAV)
#define AUDIO_EXTENSION_WAV "wav"
#define AUDIO_EXTENSION_WAV_W                                       WIDEN_STRING(AUDIO_EXTENSION_WAV)

#define AUDIO_EXTENSION_DESCRPTION_SOUNDFOUNDRY_WAVE_64 "SoundFoundry WAVE 64"
#define AUDIO_EXTENSION_DESCRPTION_SOUNDFOUNDRY_WAVE_64_W           WIDEN_STRING(AUDIO_EXTENSION_DESCRPTION_SOUNDFOUNDRY_WAVE_64)
#define AUDIO_EXTENSION_W64 "w64"
#define AUDIO_EXTENSION_W64_W                                       WIDEN_STRING(AUDIO_EXTENSION_W64)

#define AUDIO_EXTENSION_DESCRIPTION_PSION_SERIES_3 "Psion Series 3"
#define AUDIO_EXTENSION_DESCRIPTION_PSION_SERIES_3_W                WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_PSION_SERIES_3)
#define AUDIO_EXTENSION_WVE "wve"
#define AUDIO_EXTENSION_WVE_W                                       WIDEN_STRING(AUDIO_EXTENSION_WVE)

#define AUDIO_EXTENSION_DESCRIPTION_FASTTRACKER "FastTracker's Extended Instrument"
#define AUDIO_EXTENSION_DESCRIPTION_FASTTRACKER_W                   WIDEN_STRING(AUDIO_EXTENSION_DESCRIPTION_FASTTRACKER)
#define AUDIO_EXTENSION_XI "xi"
#define AUDIO_EXTENSION_XI_W                                        WIDEN_STRING(AUDIO_EXTENSION_XI)

/*******************************************************************************
*******************************************************************************/

#define THREE_STRINGS_CONCAT(a, b, c) a b c
#define THREE_STRINGS_CONCAT_W_HELPER(a, b, c, d) d##a d##b d##c
#define THREE_STRINGS_CONCAT_W(a, b, c) THREE_STRINGS_CONCAT_W_HELPER(a, b, c, L)
#define HYPHEN_CONCAT(a, b) THREE_STRINGS_CONCAT(a, "-", b)
#define HYPHEN_CONCAT_W(a, b) THREE_STRINGS_CONCAT_W(a, "-", b)
#define SPACE_CONCAT(a, b) THREE_STRINGS_CONCAT(a, " ", b)
#define SPACE_CONCAT_W(a, b) THREE_STRINGS_CONCAT_W(a, " ", b)

#define MPG123_DECODER_NAME "Mpg123 Decoder"
#define MPG123_DECODER_NAME_W WIDEN_STRING(MPG123_DECODER_NAME)

#define SNDFILE_DECODER_NAME "Sndfile Decoder"
#define SNDFILE_DECODER_NAME_W WIDEN_STRING(SNDFILE_DECODER_NAME)

#define LAME_ENCODER_NAME "LAME Encoder"
#define LAME_ENCODER_NAME_W                                         WIDEN_STRING(LAME_ENCODER_NAME)
#define PROFILE_EXTENSION_DESCRIPTION_LAME                          SPACE_CONCAT(LAME_ENCODER_NAME, "Profile")
#define PROFILE_EXTENSION_DESCRIPTION_LAME_W                        SPACE_CONCAT_W(LAME_ENCODER_NAME, "Profile")
#define PROFILE_EXTENSION_LAME "lame"
#define PROFILE_EXTENSION_LAME_W WIDEN_STRING(PROFILE_EXTENSION_LAME)

#define PROFILE_EXTENSION_LAME_MP3                                  HYPHEN_CONCAT(PROFILE_EXTENSION_LAME, AUDIO_EXTENSION_MP3)
#define PROFILE_EXTENSION_LAME_MP3_W                                HYPHEN_CONCAT_W(PROFILE_EXTENSION_LAME, AUDIO_EXTENSION_MP3)

#define SNDFILE_ENCODER_NAME "Sndfile Encoder"
#define SNDFILE_ENCODER_NAME_W                                      WIDEN_STRING(SNDFILE_ENCODER_NAME)
#define PROFILE_EXTENSION_DESCRIPTION_SNDFILE_ENCODER               SPACE_CONCAT(SNDFILE_ENCODER_NAME, "Profile")
#define PROFILE_EXTENSION_DESCRIPTION_SNDFILE_ENCODER_W             SPACE_CONCAT_W(SNDFILE_ENCODER_NAME, "Profile")
#define PROFILE_EXTENSION_SNDFILE_ENCODER "sndfe"
#define PROFILE_EXTENSION_SNDFILE_ENCODER_W WIDEN_STRING(PROFILE_EXTENSION_SNDFILE_ENCODER)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIF                      HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIF_W                    HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIFC                      HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIFC)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIFC_W                    HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIFC)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIFF                      HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIFF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AIFF_W                    HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AIFF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AMPC                      HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AMPC)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AMPC_W                    HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AMPC)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AU                        HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AU)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AU_W                      HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AU)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_AVR                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AVR)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_AVR_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_AVR)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_CAF                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_CAF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_CAF_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_CAF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_HTK                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_HTK)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_HTK_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_HTK)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_IFF                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_IFF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_IFF_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_IFF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_MAT                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_MAT)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_MAT_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_MAT)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_PAF                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_PAF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_PAF_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_PAF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_PVF                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_PVF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_PVF_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_PVF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_RF64                      HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_RF64)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_RF64_W                    HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_RF64)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_SD2                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SD2)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_SD2_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SD2)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_SDS                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SDS)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_SDS_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SDS)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_SF                        HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SF)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_SF_W                      HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_SF)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_VOC                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_VOC)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_VOC_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_VOC)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_WAV                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_WAV)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_WAV_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_WAV)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_W64                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_W64)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_W64_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_W64)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_WVE                       HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_WVE)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_WVE_W                     HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_WVE)

#define PROFILE_EXTENSION_SNDFILE_ENCODER_XI                        HYPHEN_CONCAT(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_XI)
#define PROFILE_EXTENSION_SNDFILE_ENCODER_XI_W                      HYPHEN_CONCAT_W(PROFILE_EXTENSION_SNDFILE_ENCODER, AUDIO_EXTENSION_XI)

/*******************************************************************************
*******************************************************************************/

#define LAME_ALGORITHM_QUALITY_DATA_TYPE uint8_t
#define LAME_MODE_DATA_TYPE uint8_t
#define LAME_REPLAYGAIN_DATA_TYPE uint8_t
#define LAME_BITRATE_ENCODING_DATA_TYPE uint8_t
#define LAME_BITRATE_DATA_TYPE uint16_t

#define SNDFILE_ENCODER_OUTPUT_FORMAT_DATA_TYPE uint32_t

#endif